dist: trusty
sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.13.0
  - 2.12.9

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "CW26CKE+RNijcggqHpZvZTmpqEGN678qLHcdd5OjOqBlF8pX8Pwypq+Xr7GBsQReVm15ULYDYphTemRAFKnMIgVyWeNflD2bresn64s9RMGwIjM63SSk+w7FaiU5WfkVoMlN0Cc00eVTX88dwWm1Ax8eFEd1inzdNjlxd2nYR8VTRrpVvCJybhByrgdQG0IELFbxQ5FWIY6EL1S3peIAz9nkENMjVZ3YZHm+TUbUckbk5CSoDbeKVk7Ormvb5/0dMITX4gz/EStueOk/kNUwp2veQBvnZZpmFvDxS/24PXfCsaj4g+rg3NGGneDYJIfftFWSH7ayHhhPrz9HuR6hv8jl5uZxp0Y4bz/0kzNBS9LFOwWB8ZDChR2rFFGhoGY9Bd/en/hmIYWcDPAPtwDkEFhC43lPMiRA9vyl8XFQRQR7KPsOvAbVEwZbASW9uVk3c41/IWZ8fiftjp1lOadnc8srVnskPVzuTwHF1HZMtEzzeCPqi9Yfc8mZaL/rTBcbdx+botqix60lbfDt8745BjhWSvWZmzND+YMrRR4mAkiegbq5CXaGmKAbHzzs11SWFUAVBZQYvi6ji86RXh/mM36A1ZIS6moUQEPIiknIoiHOyxwh8LtSVpNqTapKund52dL8LefI8xqtxT+u/3S++VyrX5nBMR1k6RtYcnlUXZw="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
